version: "3.1"
#Indicamos la version de docker compose que utilizamos
#Y luego los servicios que vamos a implementar
services:
    db:
        image: mysql
        container_name: sql
        ports:
            - "3308:3308"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            #Base de datos que utilizaremos.
            MYSQ_DATABASE: DB_jesus 
            #Contraseña para root.
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    php:
        build:
            #Indicamos la carpeta dodne guardamos el Docker File
            context: ./Dockerfile
            #Indicamos el archivo dockerfile de este contenedor
            dockerfile: Dockerfile
        ports:
            - "9090:80"
        volumes:
            #Indicamos con quien va relacionado
            - ./pagina:/var/www/html
        links:
             #Indicamos con quien va relacionado
            - db
        networks:
            - default
        container_name: servidorphp2
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin2
        links: 
            #Indicamos con quien va relacionado
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: 1234
volumes:
    persistent:
